kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: se4sci-postgres
spec:
  storageClassName: ibmc-file-gold
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

