apiVersion: v1
kind: Service
metadata:
  name: fire-incidents
spec:
  selector:
    app: fire-incidents
  type: NodePort
  internalTrafficPolicy: Local
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
